version: '3'
services:
  db:
    image: postgres:9.6.17
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
    volumes:
      - db-data:/var/lib/postgresql/data      
networks: 
  postgres-compose-network:
    driver: bridge
volumes:
  db-data:
    driver: local
